export const generatedMixcloudArchive = [
  {
    "id": "skull-county-radio-weird-late-night-fm-5292026",
    "title": "Weird Late Night FM 5.29.2026",
    "showName": "Weird Late-Night FM",
    "showSlug": "weird-late-night-fm",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/weird-late-night-fm-5292026/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/weird-late-night-fm-5292026/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/2/b/0/7/ebbf-9ee9-438f-a7a7-fd627a5afc19",
    "publishedAt": "2026-05-30T19:08:18Z",
    "createdAt": "2026-05-30T19:08:18Z",
    "date": "May 30, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/2/b/0/7/ebbf-9ee9-438f-a7a7-fd627a5afc19",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/weird-late-night-fm-5292026/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-house-party-frequency-5292026",
    "title": "House Party Frequency 5.29.2026",
    "showName": "House Party Frequency",
    "showSlug": "house-party-frequency",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/house-party-frequency-5292026/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/house-party-frequency-5292026/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/9/6/d/8/c41c-fdd9-44e6-94fe-e5b4bbd1d883",
    "publishedAt": "2026-05-30T19:03:19Z",
    "createdAt": "2026-05-30T19:03:19Z",
    "date": "May 30, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/9/6/d/8/c41c-fdd9-44e6-94fe-e5b4bbd1d883",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/house-party-frequency-5292026/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-dusty-crates-hip-hop-5292026",
    "title": "Dusty Crates Hip Hop 5.29.2026",
    "showName": "Dusty Crate Hip-Hop Hour",
    "showSlug": "dusty-crate-hip-hop-hour",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/dusty-crates-hip-hop-5292026/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/dusty-crates-hip-hop-5292026/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/f/f/6/5339-5542-4b93-99ae-d624205542b4",
    "publishedAt": "2026-05-30T18:49:33Z",
    "createdAt": "2026-05-30T18:49:33Z",
    "date": "May 30, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/f/f/6/5339-5542-4b93-99ae-d624205542b4",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/dusty-crates-hip-hop-5292026/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-deep-diving",
    "title": "Deep Diving",
    "showName": "Deep Diving",
    "showSlug": "deep-diving",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/deep-diving/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/deep-diving/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/0/f/9/d9da-9792-4e25-b42b-7aa1eb8fb258",
    "publishedAt": "2026-05-25T00:37:59Z",
    "createdAt": "2026-05-25T00:37:59Z",
    "date": "May 24, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/0/f/9/d9da-9792-4e25-b42b-7aa1eb8fb258",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/deep-diving/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-reflections",
    "title": "Reflections",
    "showName": "Reflections",
    "showSlug": "reflections",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/reflections/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/reflections/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/e/b/6/1/6094-11d7-43bb-8b34-772974cdafab",
    "publishedAt": "2026-05-25T00:30:52Z",
    "createdAt": "2026-05-25T00:30:52Z",
    "date": "May 24, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/e/b/6/1/6094-11d7-43bb-8b34-772974cdafab",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/reflections/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-innaminnit",
    "title": "Innaminnit",
    "showName": "Innaminnit",
    "showSlug": "innaminnit",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/innaminnit/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/innaminnit/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/3/2/2/649a-6a90-4e2e-8fe3-6adec4f0620d",
    "publishedAt": "2026-05-25T00:22:03Z",
    "createdAt": "2026-05-25T00:22:03Z",
    "date": "May 24, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/3/2/2/649a-6a90-4e2e-8fe3-6adec4f0620d",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/innaminnit/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-bar-room-jukebox-51426",
    "title": "Alt Rock Bar Room 5.14.26",
    "showName": "Alt-Rock Barroom Radio",
    "showSlug": "alt-rock-barroom-radio",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/bar-room-jukebox-51426/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/bar-room-jukebox-51426/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/b/7/8/30fa-5248-4da1-9a19-ab18d6161ea4",
    "publishedAt": "2026-05-15T06:08:02Z",
    "createdAt": "2026-05-15T06:08:02Z",
    "date": "May 14, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/b/7/8/30fa-5248-4da1-9a19-ab18d6161ea4",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/bar-room-jukebox-51426/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-golden-era-groove-51426",
    "title": "Golden Hour Groove 5.14.26",
    "showName": "Golden Hour Groove",
    "showSlug": "golden-hour-groove",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/golden-era-groove-51426/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/golden-era-groove-51426/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/2/b/6/ee13-cad7-4ee0-8e9f-cf2fdc0daed0",
    "publishedAt": "2026-05-15T05:39:47Z",
    "createdAt": "2026-05-15T05:39:47Z",
    "date": "May 14, 2026",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/2/b/6/ee13-cad7-4ee0-8e9f-cf2fdc0daed0",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/golden-era-groove-51426/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-friends-with-monsters-monsters-side",
    "title": "Friends with Monsters - Monsters Side",
    "showName": "Friends with Monsters - Monsters Side",
    "showSlug": "friends-with-monsters-monsters-side",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/friends-with-monsters-monsters-side/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/friends-with-monsters-monsters-side/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/a/c/d/b343-cdac-41c3-9176-52a38ac2415a",
    "publishedAt": "2025-08-20T02:23:29Z",
    "createdAt": "2025-08-20T02:23:29Z",
    "date": "August 19, 2025",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/a/c/d/b343-cdac-41c3-9176-52a38ac2415a",
    "externalUrl": "https://www.mixcloud.com/gdyken/friends-with-monsters-monsters-side/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-dreams-unseen",
    "title": "Dreams Unseen",
    "showName": "Dreams Unseen",
    "showSlug": "dreams-unseen",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/dreams-unseen/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/dreams-unseen/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/a/d/1/9790-ac96-4c97-8066-6af21f935c3e",
    "publishedAt": "2024-11-13T03:38:39Z",
    "createdAt": "2024-11-13T03:38:39Z",
    "date": "November 12, 2024",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/a/d/1/9790-ac96-4c97-8066-6af21f935c3e",
    "externalUrl": "https://www.mixcloud.com/gdyken/dreams-unseen/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-friends-with-monsters-friends-side",
    "title": "Friends with Monsters - Friends Side",
    "showName": "Friends with Monsters - Friends Side",
    "showSlug": "friends-with-monsters-friends-side",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/friends-with-monsters-friends-side/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/friends-with-monsters-friends-side/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/9/9/c/c/83e3-6b66-47df-9f7f-2e6d5c9885c0",
    "publishedAt": "2024-11-11T20:57:45Z",
    "createdAt": "2024-11-11T20:57:45Z",
    "date": "November 11, 2024",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/9/9/c/c/83e3-6b66-47df-9f7f-2e6d5c9885c0",
    "externalUrl": "https://www.mixcloud.com/gdyken/friends-with-monsters-friends-side/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-lonely-hertz-club",
    "title": "Lonely Hertz Club",
    "showName": "Lonely Hertz Club",
    "showSlug": "lonely-hertz-club",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/lonely-hertz-club/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/lonely-hertz-club/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/c/4/4/a0b1-7d95-4cee-9798-e441f7f1dd53",
    "publishedAt": "2022-04-25T19:06:37Z",
    "createdAt": "2022-04-25T19:06:37Z",
    "date": "April 25, 2022",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/c/4/4/a0b1-7d95-4cee-9798-e441f7f1dd53",
    "externalUrl": "https://www.mixcloud.com/gdyken/lonely-hertz-club/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-weapons-of-micro-agression",
    "title": "Weapons of Micro Agression",
    "showName": "Weapons of Micro Agression",
    "showSlug": "weapons-of-micro-agression",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/weapons-of-micro-agression/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/weapons-of-micro-agression/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/4/1/5/5/0737-337c-4698-9b8b-3240bafc3d83",
    "publishedAt": "2022-04-21T01:54:53Z",
    "createdAt": "2022-04-21T01:54:53Z",
    "date": "April 20, 2022",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/4/1/5/5/0737-337c-4698-9b8b-3240bafc3d83",
    "externalUrl": "https://www.mixcloud.com/gdyken/weapons-of-micro-agression/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-chronicles-of-boom-bap-part-1",
    "title": "Chronicles of Boom Bap part 1",
    "showName": "Chronicles of Boom Bap part 1",
    "showSlug": "chronicles-of-boom-bap-part-1",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/chronicles-of-boom-bap-part-1/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/chronicles-of-boom-bap-part-1/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/8/9/e/eecb-38ca-4298-b814-d1e35ad5d2f9",
    "publishedAt": "2020-05-02T01:08:39Z",
    "createdAt": "2020-05-02T01:08:39Z",
    "date": "May 1, 2020",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/8/9/e/eecb-38ca-4298-b814-d1e35ad5d2f9",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/chronicles-of-boom-bap-part-1/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-bboy-bbq-1",
    "title": "BBoy BBQ 1",
    "showName": "BBoy BBQ 1",
    "showSlug": "bboy-bbq-1",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/bboy-bbq-1/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/bboy-bbq-1/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/d/5/a/ebe9-2894-4bb8-b043-bb3b9499cbb3",
    "publishedAt": "2020-04-07T03:00:28Z",
    "createdAt": "2020-04-07T03:00:28Z",
    "date": "April 6, 2020",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/d/5/a/ebe9-2894-4bb8-b043-bb3b9499cbb3",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/bboy-bbq-1/",
    "platform": "Mixcloud"
  },
  {
    "id": "skull-county-radio-rest-in-power-nipsey-hussle-part-1",
    "title": "Rest In Power Nipsey Hussle part 1",
    "showName": "Rest In Power Nipsey Hussle part 1",
    "showSlug": "rest-in-power-nipsey-hussle-part-1",
    "host": "Skull County Radio",
    "djName": "Skull County Radio",
    "sourceId": "skull-county-radio",
    "sourceLabel": "Skull County Radio",
    "mixcloudUsername": "skullcountyradio",
    "mixcloudKey": "/skullcountyradio/rest-in-power-nipsey-hussle-part-1/",
    "mixcloudUrl": "https://www.mixcloud.com/skullcountyradio/rest-in-power-nipsey-hussle-part-1/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/profile/1/2/7/1/7d90-9bf4-4cf4-939d-533c416093db",
    "publishedAt": "2020-03-25T20:21:37Z",
    "createdAt": "2020-03-25T20:21:37Z",
    "date": "March 25, 2020",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/profile/1/2/7/1/7d90-9bf4-4cf4-939d-533c416093db",
    "externalUrl": "https://www.mixcloud.com/skullcountyradio/rest-in-power-nipsey-hussle-part-1/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-breaks-episode-6",
    "title": "SMOKE BREAKS * EPISODE 6",
    "showName": "SMOKE BREAKS * EPISODE 6",
    "showSlug": "smoke-breaks-episode-6",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-breaks-episode-6/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-episode-6/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/7/1/5/48ff-eedc-4abf-9cb4-d7390a581418",
    "publishedAt": "2016-08-02T04:56:02Z",
    "createdAt": "2016-08-02T04:56:02Z",
    "date": "August 1, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/7/1/5/48ff-eedc-4abf-9cb4-d7390a581418",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-episode-6/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-reflections",
    "title": "Reflections",
    "showName": "Reflections",
    "showSlug": "reflections",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/reflections/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/reflections/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/1/3/1/0/fa93-7db1-410c-bbfc-646c8749cbcb",
    "publishedAt": "2016-07-06T04:24:59Z",
    "createdAt": "2016-07-06T04:24:59Z",
    "date": "July 5, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/1/3/1/0/fa93-7db1-410c-bbfc-646c8749cbcb",
    "externalUrl": "https://www.mixcloud.com/gdyken/reflections/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-breaks-ep05",
    "title": "SMOKE BREAKS EP05",
    "showName": "SMOKE BREAKS EP05",
    "showSlug": "smoke-breaks-ep05",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-breaks-ep05/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep05/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/7/5/1/76a0-311a-4c61-84d0-cd85dc647e5f.jpg",
    "publishedAt": "2016-04-02T19:14:42Z",
    "createdAt": "2016-04-02T19:14:42Z",
    "date": "April 2, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/7/5/1/76a0-311a-4c61-84d0-cd85dc647e5f.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep05/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-breaks-ep04",
    "title": "Smoke Breaks EP04",
    "showName": "Smoke Breaks EP04",
    "showSlug": "smoke-breaks-ep04",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-breaks-ep04/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep04/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/a/3/7/1238-08f8-406d-b7f9-391fc78130ae.jpg",
    "publishedAt": "2016-02-06T05:35:44Z",
    "createdAt": "2016-02-06T05:35:44Z",
    "date": "February 5, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/a/a/3/7/1238-08f8-406d-b7f9-391fc78130ae.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep04/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-breaks-ep03",
    "title": "SMOKE BREAKS EP03",
    "showName": "SMOKE BREAKS EP03",
    "showSlug": "smoke-breaks-ep03",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-breaks-ep03/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep03/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/d/3/f/b/d7f1-0162-4b10-9182-e1ec501cc572.jpg",
    "publishedAt": "2016-01-23T21:06:46Z",
    "createdAt": "2016-01-23T21:06:46Z",
    "date": "January 23, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/d/3/f/b/d7f1-0162-4b10-9182-e1ec501cc572.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-ep03/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-breaks-2",
    "title": "Smoke Breaks 2",
    "showName": "Smoke Breaks 2",
    "showSlug": "smoke-breaks-2",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-breaks-2/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-2/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/4/7/7/d/a430-42fa-41b7-85f4-cfd96304c1ba.jpg",
    "publishedAt": "2016-01-17T07:26:33Z",
    "createdAt": "2016-01-17T07:26:33Z",
    "date": "January 16, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/4/7/7/d/a430-42fa-41b7-85f4-cfd96304c1ba.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-breaks-2/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-smoke-break",
    "title": "Smoke Break",
    "showName": "Smoke Break",
    "showSlug": "smoke-break",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/smoke-break/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/smoke-break/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/7/2/e/7c2c-2907-4041-9623-8d1e7aeea4c0.jpg",
    "publishedAt": "2016-01-08T07:41:51Z",
    "createdAt": "2016-01-08T07:41:51Z",
    "date": "January 7, 2016",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/7/2/e/7c2c-2907-4041-9623-8d1e7aeea4c0.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/smoke-break/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-n3bula-blu3s",
    "title": "NEBULA BLUES",
    "showName": "NEBULA BLUES",
    "showSlug": "nebula-blues",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/n3bula-blu3s/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/n3bula-blu3s/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/b/a/8/034e-f814-44f3-8893-37f517daf3a7.jpg",
    "publishedAt": "2015-08-06T05:48:06Z",
    "createdAt": "2015-08-06T05:48:06Z",
    "date": "August 5, 2015",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/b/a/8/034e-f814-44f3-8893-37f517daf3a7.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/n3bula-blu3s/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-deep-diving",
    "title": "Deep Diving",
    "showName": "Deep Diving",
    "showSlug": "deep-diving",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/deep-diving/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/deep-diving/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/c/e/f/4c47-3541-4a24-8d4f-f27024497a3d.jpg",
    "publishedAt": "2015-04-23T07:43:11Z",
    "createdAt": "2015-04-23T07:43:11Z",
    "date": "April 23, 2015",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/c/e/f/4c47-3541-4a24-8d4f-f27024497a3d.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/deep-diving/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-off-the-chain",
    "title": "Off the Chain!",
    "showName": "Off the Chain!",
    "showSlug": "off-the-chain",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/off-the-chain/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/off-the-chain/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/7/d/2/b/4a85-c31e-445d-92a4-4aab2d95dcc1.jpg",
    "publishedAt": "2015-01-12T03:06:51Z",
    "createdAt": "2015-01-12T03:06:51Z",
    "date": "January 11, 2015",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/7/d/2/b/4a85-c31e-445d-92a4-4aab2d95dcc1.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/off-the-chain/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-spin-cycle",
    "title": "Spin Cycle",
    "showName": "Spin Cycle",
    "showSlug": "spin-cycle",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/spin-cycle/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/spin-cycle/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/1/0/1/fe71-6603-41c1-a789-0c27fa8e8938.jpg",
    "publishedAt": "2014-12-07T05:21:37Z",
    "createdAt": "2014-12-07T05:21:37Z",
    "date": "December 6, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/1/0/1/fe71-6603-41c1-a789-0c27fa8e8938.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/spin-cycle/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-fallout-detroit",
    "title": "Fallout: Detroit",
    "showName": "Fallout: Detroit",
    "showSlug": "fallout-detroit",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/fallout-detroit/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/fallout-detroit/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/6/8/2/846f-ac31-470b-843c-4e60e20db48e.jpg",
    "publishedAt": "2014-09-26T05:24:08Z",
    "createdAt": "2014-09-26T05:24:08Z",
    "date": "September 25, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/6/8/2/846f-ac31-470b-843c-4e60e20db48e.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/fallout-detroit/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-silver-lining",
    "title": "Silver Lining",
    "showName": "Silver Lining",
    "showSlug": "silver-lining",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/silver-lining/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/silver-lining/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/e/3/6/8fb7-e319-4fc0-bbef-f748cdd4552c.jpg",
    "publishedAt": "2014-09-14T21:15:55Z",
    "createdAt": "2014-09-14T21:15:55Z",
    "date": "September 14, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/e/3/6/8fb7-e319-4fc0-bbef-f748cdd4552c.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/silver-lining/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-lovers-sinners",
    "title": "Lovers & Sinners",
    "showName": "Lovers & Sinners",
    "showSlug": "lovers-sinners",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/lovers-sinners/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/lovers-sinners/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/2/6/8/d/2c8e-6f79-4917-8514-8525be40b0cc.jpg",
    "publishedAt": "2014-07-04T15:41:07Z",
    "createdAt": "2014-07-04T15:41:07Z",
    "date": "July 4, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/2/6/8/d/2c8e-6f79-4917-8514-8525be40b0cc.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/lovers-sinners/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-imagine-baggins-back-there-again",
    "title": "Imagine Baggins: Back & There Again",
    "showName": "Imagine Baggins: Back & There Again",
    "showSlug": "imagine-baggins-back-there-again",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/imagine-baggins-back-there-again/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/imagine-baggins-back-there-again/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/d/d/1/61cc-67ed-4c97-a83c-de99ebca2092.jpg",
    "publishedAt": "2014-06-13T21:28:13Z",
    "createdAt": "2014-06-13T21:28:13Z",
    "date": "June 13, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/c/d/d/1/61cc-67ed-4c97-a83c-de99ebca2092.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/imagine-baggins-back-there-again/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-permanent-vacation",
    "title": "Permanent Vacation",
    "showName": "Permanent Vacation",
    "showSlug": "permanent-vacation",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/permanent-vacation/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/permanent-vacation/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/d/d/5/8/4192-cefe-4558-94ba-277f3da598de.jpg",
    "publishedAt": "2014-05-28T19:23:37Z",
    "createdAt": "2014-05-28T19:23:37Z",
    "date": "May 28, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/d/d/5/8/4192-cefe-4558-94ba-277f3da598de.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/permanent-vacation/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-candi-wants-2-dance",
    "title": "Candi Wants 2 Dance",
    "showName": "Candi Wants 2 Dance",
    "showSlug": "candi-wants-2-dance",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/candi-wants-2-dance/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/candi-wants-2-dance/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/0/d/7/f98f-082d-4e43-ab45-7441ed46246e.jpg",
    "publishedAt": "2014-05-11T06:50:39Z",
    "createdAt": "2014-05-11T06:50:39Z",
    "date": "May 10, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/0/d/7/f98f-082d-4e43-ab45-7441ed46246e.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/candi-wants-2-dance/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-into-the-forest",
    "title": "Into the Forest",
    "showName": "Into the Forest",
    "showSlug": "into-the-forest",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/into-the-forest/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/into-the-forest/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/9/4/9/a23d-96f9-45d1-8e5c-eead5ab5a718.jpg",
    "publishedAt": "2014-05-10T08:17:47Z",
    "createdAt": "2014-05-10T08:17:47Z",
    "date": "May 10, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/9/4/9/a23d-96f9-45d1-8e5c-eead5ab5a718.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/into-the-forest/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-holes-in-my-soles",
    "title": "Holes in My Soles",
    "showName": "Holes in My Soles",
    "showSlug": "holes-in-my-soles",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/holes-in-my-soles/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/holes-in-my-soles/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/f/1/8/13fb-555d-436e-865e-a0eda96ccbf7.jpg",
    "publishedAt": "2014-05-07T06:17:30Z",
    "createdAt": "2014-05-07T06:17:30Z",
    "date": "May 6, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/8/f/1/8/13fb-555d-436e-865e-a0eda96ccbf7.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/holes-in-my-soles/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-get-rekt",
    "title": "Get Rekt",
    "showName": "Get Rekt",
    "showSlug": "get-rekt",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/get-rekt/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/get-rekt/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/0/5/1/0/dc5b-75b0-49cc-a6c1-60468494b61c.jpg",
    "publishedAt": "2014-03-22T05:16:29Z",
    "createdAt": "2014-03-22T05:16:29Z",
    "date": "March 21, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/0/5/1/0/dc5b-75b0-49cc-a6c1-60468494b61c.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/get-rekt/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-parlour-house",
    "title": "Parlour House",
    "showName": "Parlour House",
    "showSlug": "parlour-house",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/parlour-house/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/parlour-house/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/a/8/5/0585-54af-4e0e-9575-240135fcccc5.jpg",
    "publishedAt": "2014-03-22T02:06:28Z",
    "createdAt": "2014-03-22T02:06:28Z",
    "date": "March 21, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/b/a/8/5/0585-54af-4e0e-9575-240135fcccc5.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/parlour-house/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-nekyd-soul",
    "title": "Nekyd Soul",
    "showName": "Nekyd Soul",
    "showSlug": "nekyd-soul",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/nekyd-soul/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/nekyd-soul/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/1/9/5/7/3c8a-574b-4f9a-9871-c28bb6f804f9.jpg",
    "publishedAt": "2014-03-22T01:49:45Z",
    "createdAt": "2014-03-22T01:49:45Z",
    "date": "March 21, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/1/9/5/7/3c8a-574b-4f9a-9871-c28bb6f804f9.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/nekyd-soul/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-dub-in-my-step-2010",
    "title": "Smoke Hill",
    "showName": "Smoke Hill",
    "showSlug": "smoke-hill",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/dub-in-my-step-2010/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/dub-in-my-step-2010/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/4/6/1/df2b-b912-4628-bf0d-990603c00510.jpg",
    "publishedAt": "2014-03-11T00:13:54Z",
    "createdAt": "2014-03-11T00:13:54Z",
    "date": "March 10, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/f/4/6/1/df2b-b912-4628-bf0d-990603c00510.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/dub-in-my-step-2010/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-magic-bullet",
    "title": "Magic Bullet",
    "showName": "Magic Bullet",
    "showSlug": "magic-bullet",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/magic-bullet/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/magic-bullet/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/3/8/2/ab78-1c30-493d-a370-bd8598344547.jpg",
    "publishedAt": "2014-02-26T08:31:30Z",
    "createdAt": "2014-02-26T08:31:30Z",
    "date": "February 26, 2014",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/3/3/8/2/ab78-1c30-493d-a370-bd8598344547.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/magic-bullet/",
    "platform": "Mixcloud"
  },
  {
    "id": "dj-aquarobotics-cymbolic-techno",
    "title": "Cymbolic Techno",
    "showName": "Cymbolic Techno",
    "showSlug": "cymbolic-techno",
    "host": "DJ Aquarobotics",
    "djName": "DJ Aquarobotics",
    "sourceId": "dj-aquarobotics",
    "sourceLabel": "DJ Aquarobotics",
    "mixcloudUsername": "gdyken",
    "mixcloudKey": "/gdyken/cymbolic-techno/",
    "mixcloudUrl": "https://www.mixcloud.com/gdyken/cymbolic-techno/",
    "embedUrl": "",
    "imageUrl": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/3/f/8/dec8-b2ab-45f3-b387-77b892639e2a.jpg",
    "publishedAt": "2013-12-12T21:18:46Z",
    "createdAt": "2013-12-12T21:18:46Z",
    "date": "December 12, 2013",
    "artwork": "https://thumbnailer.mixcloud.com/unsafe/600x600/extaudio/5/3/f/8/dec8-b2ab-45f3-b387-77b892639e2a.jpg",
    "externalUrl": "https://www.mixcloud.com/gdyken/cymbolic-techno/",
    "platform": "Mixcloud"
  }
];
